language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
virtualenv:
  system_site_packages: true
install:
  - pip install -e .
  - pip install coveralls
  - pip install flake8
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
